### ISSUE TITLE
Content of words.json

### ISSUE THREAD

**Issue by yamaszone** [masonwan/tweentiment#14]
should the content of /res/words.json file remained unchanged all the time? it always shows 26 rows as its content. I am investigating the sentiment results accuracy and came across it.

**Comment by masonwan** [comment]
@yamaszone It will change when new word was found.

**Comment by yamaszone** [comment]
I have been trying with lots of random search keywords but the content never changes. This may be one of the reasons for incorrect sentiment classification.
